### ISSUE TITLE
Electric Story Maps, Set 1

### ISSUE THREAD

**Issue by jalsup** [Esri/utility-network-modeling#155]
First set of Electric Story Maps

Mike had already done one for a Fused Overhead Three Phase (the photo is wrong, it is of a unfused three phase tap)

For additional story maps, let's do the following
 - [ ] Modeling Electric Wires Detail
       - UN Diagram: https://github.com/Esri/utility-network-modeling/blob/dev/Electric/General/Modeling%20line%20to%20wires.pdf
 - [ ] Distribution Substation Bus work
       - UN Diagram: utility-network-modeling/Electric/General/Modeling wire spacing.pdf
 - [ ] Two Versions of Distribution Single Phase Transformer (Wye and Delta configurations)
       - UN Diagram for Wye: https://github.com/Esri/utility-network-modeling/blob/dev/Electric/Distribution/Overhead%20Single%20Phase%20Transformer%20with%20Services/Overhead%20Single%20Phase%20Transformer%20with%20Services.pdf
       - UN Diagram for Delta: https://github.com/Esri/utility-network-modeling/blob/dev/Electric/Distribution/Overhead%20Single%20Phase%20Transformer/Overhead%20Single%20Phase%20Dual%20Voltage%20Transformer%20Bank.pdf
  - [ ] Overhead three phase recloser with dual transformers
       - UN Diagram:https://github.com/Esri/utility-network-modeling/tree/dev/Electric/Distribution/Overhead%20Three%20Phase%20Recloser%20With%20Dual%20Transformers

**Comment by avezina** [comment]
Here are the first drafts for the Story Maps. Of course, images will need to be added, and I assume there is missing text/text touch-ups required.

Modeling Electric Wires Detail: https://utilsoldeploy.maps.arcgis.com/apps/Cascade/index.html?appid=04443d9a47c345bcb6d7566148d420f6

Overhead Bidirectional Three Phase Recloser: https://utilsoldeploy.maps.arcgis.com/apps/Cascade/index.html?appid=bcca0df1d0c044838753948b871da0df

Overhead Fused Three Phase Tap: https://utilsoldeploy.maps.arcgis.com/apps/Cascade/index.html?appid=57eb8b39ae604c86a99ca538747f314e

Distribution Single Phase Transformer (Delta): https://utilsoldeploy.maps.arcgis.com/apps/Cascade/index.html?appid=7ba273cb47f742e8be39914bc3dcbd54

Distribution Single Phase Transformer (Wye): https://utilsoldeploy.maps.arcgis.com/apps/Cascade/index.html?appid=523b8c9a109f458bb91c554bbad1c7f8

Modeling Wire Spacing: https://utilsoldeploy.maps.arcgis.com/apps/Cascade/index.html?appid=ffe08f9bb8a248549417ca922cf27a03

**Comment by jalsup** [comment]
Let's change the wording "Advantages" to "Capabilities".

For the "Modeling Electric Wires Detail' diagram, let's also add the following comment:
-Supports having multiple conductors per phase
-Supports mixed conductors per phase
-Supports lifecycle status of wires per phase, allowing for electric system upgrades

For diagram "Overhead Bidirectional Three Phase Recloser", add the following for Capabilities:
-includes controller 
-demonstrates recloser device operation receiving power from internal transformers and which phase the device is connected to and on which side of the recloser they are connected

For diagram "Modeling Wire Spacing", add the capabilities:
-Accurately stores information about conductor separation and conductor height relative to ground

**Comment by avezina** [comment]
@jalsup We need to look into finding the images for these Story Maps. Let me know if you already have some pictures we can use.

**Comment by avezina** [comment]
As discussed in our latest meeting today, I've updated our Story Maps to using the Beta version. Here are the new links:

Modeling Electric Wires Detail: https://storymaps-nextgen.arcgis.com/beta/stories/c957d7a091be4b1e942b5c82883f6f66

Overhead Bidirectional Three Phase Recloser: https://storymaps-nextgen.arcgis.com/beta/stories/2820bfea785a48a4bd72463a9b3caccf

Overhead Fused Three Phase Tap: https://storymaps-nextgen.arcgis.com/beta/stories/01a45dea930443be9a266d3eb2f27e7f

Distribution Single Phase Transformer (Delta): https://storymaps-nextgen.arcgis.com/beta/stories/0d36480c1369428298e86ffc0b616fde

Distribution Single Phase Transformer (Wye): https://storymaps-nextgen.arcgis.com/beta/stories/fd6a3769850f4857b9dc69273256f182

Modeling Wire Spacing: https://storymaps-nextgen.arcgis.com/beta/stories/903a7b52bd644b05897395e2ccc00400

We now need to review the text and add pictures of the actual devices.

**Comment by MikeMillerGIS** [comment]
@jalsup @MichaelZeiler can we get the images for these?

**Comment by MichaelZeiler** [comment]
Yes @MikeMillerGIS I've begun compiling photos for these. I'll provide an annotated photo for every instance/story map. For now, I'm keeping them here: https://www.dropbox.com/sh/oh111qs5qgwm7rb/AACPxl_e3eVH0WCZg8lfE3w6a?dl=0

**Comment by jalsup** [comment]
here is a link to the photos Mike Z has taken or found that we can use.
https://www.dropbox.com/sh/oh111qs5qgwm7rb/AACPxl_e3eVH0WCZg8lfE3w6a?dl=0

for some reason, I cannot access the storymaps.

**Comment by avezina** [comment]
@MichaelZeiler Thank you very much for the pictures, they look great! 
I will be including them into a new version of the Story Maps and unfortunately, the program doesn't currently allow for resizing or any kind of display configuration for the images, which means that some of the image is cut out. Therefore, we will need to configure the images prior to adding them to the Story Map.
@gslyer figured out that cropping the image size ratio to 1:1 and adding a white border to the image will work.
![image](https://user-images.githubusercontent.com/50338557/59063838-d2b62800-885d-11e9-981d-d88ee533c1bd.png)

**Comment by avezina** [comment]
Here are the updated Story Map links as @jalsup pointed out that he did not have access to the previous links. Hopefully these work.

Modeling Electric Wires Detail: https://storymaps-nextgen.arcgis.com/beta/stories/c957d7a091be4b1e942b5c82883f6f66

Overhead Bidirectional Three Phase Recloser: https://storymaps-nextgen.arcgis.com/beta/stories/2820bfea785a48a4bd72463a9b3caccf

Overhead Fused Three Phase Tap: https://storymaps-nextgen.arcgis.com/beta/stories/01a45dea930443be9a266d3eb2f27e7f

Distribution Single Phase Transformer (Delta): https://storymaps-nextgen.arcgis.com/beta/stories/0d36480c1369428298e86ffc0b616fde

Distribution Single Phase Transformer (Wye): https://storymaps-nextgen.arcgis.com/beta/stories/fd6a3769850f4857b9dc69273256f182

Modeling Wire Spacing: https://storymaps-nextgen.arcgis.com/beta/stories/903a7b52bd644b05897395e2ccc00400

**Comment by MichaelZeiler** [comment]
@avezina Great, I'll glad they look good. But let's get the image size nailed. Can you give me the target pixel size (or image aspect ratio) that works well in the story maps? I'll make the adjustment needed to get it right.

As with the data model diagrams, I'm producing an editable PDF along with JPGs. The idea is that the PDFs can be edited in the future. 

I'm working on several more now and will upload soon. I will be out of the office tomorrow, back on Monday.

**Comment by avezina** [comment]
@MichaelZeiler Thank you! Apparently, the size itself is not important, but they need to be square, so a ratio 1:1 when it comes to hight and width - say for example 1000x1000pixels, with a white background all around, say about half an inch wide. Ideally, we want to preserve the high resolution of your images. If you would like, please feel free to send me just one of the images formatted so we can make sure it's the right fit before making all the changes.

**Comment by gelisajoseph** [comment]
![image](https://user-images.githubusercontent.com/28928994/59064823-0db95b00-8860-11e9-8d62-61dcbd04610a.png)

@MichaelZeiler The header for the Story Map container is the above pixel size, hope this helps.

**Comment by MichaelZeiler** [comment]
Thank you @gslyer and @avezina , I'll make adjustments to the photos so that they are 951 x 800 pixels and I'll have another ready in 1-2 hours from now. I'll ping you when they are ready

**Comment by MichaelZeiler** [comment]
Ok @avezina and @gslyer , I've updated the photos, added one more that @jalsup requested (3 ph fused tap), changed the PDFs to double the pixel size of 951x800 to 1902x1600 px, and exported JPGs with medium compression at that size. Please test these and see if they work as expected in the story map. 
https://www.dropbox.com/sh/oh111qs5qgwm7rb/AACPxl_e3eVH0WCZg8lfE3w6a?dl=0

I'm working on other photos and will add them once you've tested these. 

I'm out Friday, back on Monday

**Comment by avezina** [comment]
@MichaelZeiler Thank you! Almost all perfect, only a display issue with the Single Phase Delta Transformer image, where some of the text is cut out. 

![image](https://user-images.githubusercontent.com/50338557/59117917-c1bff200-8903-11e9-8013-662edd07ae31.png)

**Comment by jalsup** [comment]
The story maps are helping this make sense and helping me with the flow.

But, I do have the following comments on the diagrams
Map – Overhead Bi-Directional Recloser
-Diagram does not match photo.  
    -Diagram is missing a set of three by switches used for by passing (not to be confused with a by-pass switch).
    -Each switch used as for bypass should be normally open, and indicated as such in the diagram
    -Switch Asset Group/Asset Type would be “Medium Voltage Switch/Overhead Single Phase Load Break Switch”
    -Since we will be adding the switches, comments should include “By Pass switches modeled, to support complete switching orders”

Overhead Single Phase Delta Transformer
  - Should “Characteristics be moved to below diagram or eliminated or reworded?  I would go with a general description something like:
     “Overhead Single Phase Transformer connected to two input phases (Delta) with high side current and voltage protection”

Overhead Single Phase Wye Transformer
  -Should “Demonstrates” section be eliminated?  Maybe replaced with
   “Overhead Single Phase Transformer connected to a single input phase (Wye) with high side current and voltage protection”

“Wire Spacing” 
  -Diagram needs relationship to “StructureJunction” feature modeled, like the WireData diagram did.

**Comment by avezina** [comment]
Hi @MichaelZeiler, please we still need images for 
- Modeling wire-to-wire and wire-to-ground
https://github.com/Esri/utility-network-modeling/blob/dev/Electric/General/Modeling%20wire%20spacing.pdf
- Modeling the electric wires to a line https://github.com/Esri/utility-network-modeling/blob/dev/Electric/General/Modeling%20line%20to%20wires.pdf

Thank you!

**Comment by avezina** [comment]
@jalsup regarding your previous comments, who will be able to make the change to the diagrams? Also, would you be able to indicate exactly which changes you require for the photos to @MichaelZeiler ? Thank you!

**Comment by jalsup** [comment]
the diagram does not match the photo for the bidirectional recloser.  The picture shows the bypass switch, but the diagram does not.

**Comment by MikeMillerGIS** [comment]
Can we add the bypass to the diagram?

**Comment by jalsup** [comment]
that is going to be the fastest thing to do.  I checked all the reclosers in my area and they all have bypass switches.  Does anyone have adobe illustrator?

**Comment by hCrothers** [comment]
I have Illustrator, I think @Elena9170 has it too

**Comment by avezina** [comment]
@jalsup did this image have it? 
![image](https://user-images.githubusercontent.com/50338557/59775103-6b3ca700-9265-11e9-83db-a12b329881be.png)

**Comment by jalsup** [comment]
Yes, that has two sets of switches, but is not configured for bypass.  Probably best to use the other image and add in the bypass switch (3 of them).

**Comment by jalsup** [comment]
Just spoke with Mike Z, he is going to do the following
1 - on the wire table example, he will add the neutral to the related table
2 - on the Recloser, he will add the three bypass switches configured as normally open, using Single Phase Load Break switches, as they have terminals, which will be required in this case
3 - on the Single Phase Delta transformer, he will try to crop out the switches above the transformer in the picture
4 - on the wire spacing map, he will get a picture of a overhead three phase line on a pole with no other equipment.

**Comment by MichaelZeiler** [comment]
I just spoke with @jalsup and we decided upon the following:
- Modeling electric wires story map: I'll add photo. In diagram, I'll add a neutral conductor to the table
- 3 ph bidirectional recloser story map: In the photo, I'll label arresters and load break switches. In the diagram, I'll add load break switches with terminals
- 3ph fused tap story map: get rid of arresters in diagram, not present in the photo
- 1 ph delta transformer story map: I will crop the photo to get rid of switches on the top. Adding them to the diagram will confuse and complicate this story map and obfuscate the point of how to wire a delta connection
- 1 ph wye transformer story map: good
- wire-to-wire and wire-to-ground story map: Add photo

I'll work on these now. I start a two week vacation on Friday, but will get these done

**Comment by jalsup** [comment]
Updated diagram from Mike Z for the wire data story map
[Modeling line to wires (1).pdf](https://github.com/Esri/utility-network-modeling/files/3307163/Modeling.line.to.wires.1.pdf)

**Comment by avezina** [comment]
@MichaelZeiler @jalsup would it be possible to also get the high-quality image for this one? I tried converting it but I lose quality.

**Comment by MichaelZeiler** [comment]
![Modeling line to wires](https://user-images.githubusercontent.com/5567317/59793413-5bd05480-928b-11e9-852b-57abf75ec360.jpg)
@avezina, here it is. I'm about to leave for a doctor appt, will be back in 2 hours. I'm almost done with all the items from my conversation with John this morning, will post them this afternoon when I return

**Comment by MichaelZeiler** [comment]
I've now completed all the items I've discussed with @jalsup and @avezina yesterday. In this folder, all the graphics for the six story maps now being published are ready: https://www.dropbox.com/sh/oh111qs5qgwm7rb/AACPxl_e3eVH0WCZg8lfE3w6a?dl=0

These comprise photos of the configurations in two forms: PDFs for future editing and JPGs for direct drop into the story maps. The configuration photos JPGs have resolution of 1902x1600px.

There are also diagrams for each configuration with the same file name prefix. These also comprise PDFs for future editing and JPGs for direct drop into the story maps. The diagram JPGs have resolution of 1920x1080px.

I start a two-week vacation tomorrow, so if you need further edits, let me know soon.

Also, I've done 28 other configuration diagrams with John for future story maps. These can be found in this folder: https://www.dropbox.com/sh/f644k66bjdwa2ix/AABvNbaDERorZe_S19IVXRZaa?dl=0

**Comment by avezina** [comment]
Thank you @MichaelZeiler these were all perfect for the StoryMaps.

@jalsup would you be able to do a final review to make sure all the text in the StoryMaps is complete? Here are some things I've noticed / questions I have:

**All StoryMaps** 
- The subtitle is "Best practice equipment configuration using the Electric Network Foundation for the Utility Network". Anything shorter we could use such as: "Configurations for the Electric Utility Network Foundation" ?

**Modeling Wire Spacing** - is this the correct title?
https://storymaps-nextgen.arcgis.com/beta/stories/903a7b52bd644b05897395e2ccc00400
- Provide an image caption for the diagram.
- Complete this sentence "... [??]... Demonstrates the management of conductor spacing in overhead systems. This applies to all voltage classes and tiers." ?

**Overhead Bidirectional Three Phase Recloser**  - is this the correct title?
https://storymaps-nextgen.arcgis.com/beta/stories/2820bfea785a48a4bd72463a9b3caccf
- Add an introduction/explanation text above diagram image.
- Provide an image caption for the diagram.

**Distribution Single Phase Transformer (Delta)**  - is this the correct title?
https://storymaps-nextgen.arcgis.com/beta/stories/0d36480c1369428298e86ffc0b616fde
- This is the only Story Map with characteristics? Should the other Story Maps have characteristics too?
- See Characteristic point 4 and complete/correct ##UN text?
- See Capabilities point 3, change to: "Shows one tap per phase on connections to overhead medium voltage lines **and supports** phase management."??

**Distribution Single Phase Transformer (Wye)**  - is this the correct title?
https://storymaps-nextgen.arcgis.com/beta/stories/fd6a3769850f4857b9dc69273256f182

**Overhead Fused Three Phase Tap**  - is this the correct title?
https://storymaps-nextgen.arcgis.com/beta/stories/01a45dea930443be9a266d3eb2f27e7f
 - This is and the next are the only story maps that has a full intro text "This is the best practice document for ...." -  Should we have similar text for the other story maps?

**Modeling Electric Wires Detail**  - is this the correct title?
https://storymaps-nextgen.arcgis.com/beta/stories/c957d7a091be4b1e942b5c82883f6f66
- Provide an image caption for the diagram.

**Comment by hCrothers** [comment]
The title of the product is wrong in 2nd block of text on these story maps

It’s Electric Utility Network Foundation

Also can we place a hyperlink on that name that brings people to the foundation overview page?

Get Outlook for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__aka.ms_o0ukef&d=DwIF-g&c=n6-cguzQvX_tUIrZOS_4Og&r=yhbqQ-BpoO6Q7ChW-kKa9_-AmUKtoklTE6McmgE7Bq8i8Y68xOeTPThqMFCT7JVVrgJPcnZwp-m1CqPX5S_edwBb6s4x4fmAfQNpLw2kliY&m=iOq7NEgrmaRVFdTHFpOG2c_5wYnAf6HGPCKCVZNmQJM&s=VW1dE1u6De34XHPDCfKfnDqJKIhYFa2XtuMe29dnWVg&e= >
________________________________

**Comment by avezina** [comment]
@hCrothers I'll correct the subtitle, but also I was wondering if we could potentially shorten it? for example "Configurations for the Electric Utility Network Foundation"?
It is not possible to add a hyperlink to a subtitle, unfortunately. Maybe we could add a sentence like "The electric diagrams are part of Electric Utility Network Foundation. Visit the ArcGIS Solutions Website for more information." with hyperlinks at the end of the StoryMaps?

**Comment by hCrothers** [comment]
I wouldn’t shorten it. They are best practices

I wouldn’t worry about adding that to the end. Just wanted to give an easy way to get to the Foundation if they stumbled onto the diagram.

Get Outlook for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__aka.ms_o0ukef&d=DwIF-g&c=n6-cguzQvX_tUIrZOS_4Og&r=tVzpMAM_GYDmLJyF5mjLgRhTMACEKYQPyaMdof1lyzYr-bi6rHwlCAX_pdLOQPW89ZiM9aiBdTUW5gXc8SbqFIYdzg9dSP-kWfkQdizMJC4&m=kGjr_MH1LhJ3pmdN_7ZYyyAdY-8MN90_CznVjCSU674&s=pEnvw2tSPRiu7OAHR4TQkiXRhlvYjoPOCyfe38OBk-U&e= >
________________________________

**Comment by jalsup** [comment]
answers from John Alsup
Modeling Wire Spacing - is this the correct title? yes
•	Complete this sentence "... [this example]... Demonstrates the management of conductor spacing in overhead system. This applies to all voltage classes and tiers." ?
 - Characteristics: 
   -Demonstrates wire spacing used in engineering analysis calculations

Overhead Bidirectional Three Phase Recloser - is this the correct title? yes
Distribution Single Phase Transformer (Delta) - is this the correct title? yes
 - Characteristics: 
   -Shows structural attachment of medium voltage lines and to switch bank assembly
   -Demonstrates the correct use of taps as single phase features on both medium voltage lines
   -Shows containment of eqiupment in switch bank assembly

Distribution Single Phase Transformer (Delta) - is this the correct title? yes
 - Characteristics: 
   -Shows structural attachment of medium voltage lines and to transformer bank assembly
   -Demonstrates the correct use of taps as single phase features on medium and low voltage lines 
   -Shows how the two phases can be correctly attached to the devices
   -Shows containment of equipment in transformer bank assembly

Distribution Single Phase Transformer (Wye) - is this the correct title? yes
 - Characteristics: 
   -Shows structural attachment of medium voltage lines and to transformer bank assembly
   -Demonstrates the correct use of taps as single phase features on medium and low voltage lines 
   -Shows containment of equipment in transformer bank assembly

Overhead Fused Three Phase Tap - is this the correct title?
 - Characteristics: 
   -Shows structural attachment of medium voltage lines and to fuse bank assembly
   -Demonstrates the correct use of taps as single phase features on both medium voltage lines
   -Shows containment of fuses in fuse bank assembly

Modeling Electric Wires Detail - is this the correct title? yes
-Characteristics:
  -shows the detail information for each wire associated with each phase and neutral for a conductor segment.

**Comment by avezina** [comment]
@jalsup you've listed Distribution Single Phase Transformer (Delta) 2 times, which one is correct?

**Comment by jalsup** [comment]
@avezina the second one.  Sorry.  The first one actually is for the recloser

**Comment by avezina** [comment]
This first set of StoryMaps is complete.
