### ISSUE TITLE
Drawing Tool used for model representation

### ISSUE THREAD

**Issue by anthonyryan-ergon** [Esri/utility-network-modeling#163]
Hi there,
What software/tool is used to develop the diagrams to represent the different models?
I would like to use something similar to develop models that I’m looking to develop for our implementation of the UNM.
Also, is there a template to share that contains the different symbols, line styles, colours already used?

Thanks

**Comment by jalsup** [comment]
they were all created using Adobe Illustrator.  
The person who created the diagrams is on holiday, so when he gets back, I will see if he has a template we can share.

**Comment by gprocino** [comment]
@jalsup The pdf models are very useful. May you share the template please? What about the drawing of model? Did It is create by hand using the template or there are specific plug-in for Adobe Illustrator?
