### ISSUE TITLE
Pad Mounted Three Phase Regulator

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/utility-network-modeling#98]

**Comment by jalsup** [comment]
@MichaelZeiler I found an issue with the diagram. 
The Ar in the Table of Contents should be Lb
Can you correct this for me?

**Comment by MichaelZeiler** [comment]
Fixed. PDF at https://www.dropbox.com/s/vm5kiceghbh6pqd/Pad%20Mounted%20Voltage%20Regulator%20Bank%20detail%20UN.pdf?dl=0
